import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { supabase } from '../lib/supabase'
import { fadeUp, staggerContainer, cardItem } from '../utils/animations'
import { FileText, Download, Edit3, Check, X, Trash2 } from 'lucide-react'
import LoadingScreen from '../components/LoadingScreen'

export default function NotesPage({ session }) {
  const [notes, setNotes] = useState([])
  const [subjects, setSubjects] = useState([])
  const [subtopics, setSubtopics] = useState([])
  const [loading, setLoading] = useState(true)
  const [selectedNote, setSelectedNote] = useState(null)
  const [editing, setEditing] = useState(false)
  const [editContent, setEditContent] = useState('')
  const [saving, setSaving] = useState(false)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => { fetchAll() }, [])

  async function fetchAll() {
    setLoading(true)
    const [{ data: notesData }, { data: subjectsData }, { data: subtopicsData }] = await Promise.all([
      supabase.from('notes').select('*').eq('user_id', session.user.id).order('created_at', { ascending: false }),
      supabase.from('subjects').select('*').eq('user_id', session.user.id),
      supabase.from('subtopics').select('*').eq('user_id', session.user.id),
    ])
    setNotes(notesData || [])
    setSubjects(subjectsData || [])
    setSubtopics(subtopicsData || [])
    if (notesData && notesData.length > 0) setSelectedNote(notesData[0])
    setLoading(false)
  }

  function getSubjectName(id) { return subjects.find(s => s.id === id)?.name || 'Unknown' }
  function getSubtopicName(id) { return subtopics.find(s => s.id === id)?.title || 'Unknown' }

  function formatDate(dateStr) {
    return new Date(dateStr).toLocaleDateString('en-MY', { day: 'numeric', month: 'short', year: 'numeric' })
  }

  function groupBySubject() {
    const groups = {}
    notes.forEach(note => {
      const subjectId = note.subject_id
      if (!groups[subjectId]) groups[subjectId] = []
      groups[subjectId].push(note)
    })
    return groups
  }

  async function handleSave() {
    setSaving(true)
    await supabase.from('notes').update({
      content: editContent,
      updated_at: new Date().toISOString()
    }).eq('id', selectedNote.id)
    setNotes(prev => prev.map(n => n.id === selectedNote.id ? { ...n, content: editContent } : n))
    setSelectedNote(prev => ({ ...prev, content: editContent }))
    setEditing(false)
    setSaving(false)
  }

  async function handleDelete(noteId) {
    await supabase.from('notes').delete().eq('id', noteId)
    setNotes(prev => prev.filter(n => n.id !== noteId))
    if (selectedNote?.id === noteId) {
      const remaining = notes.filter(n => n.id !== noteId)
      setSelectedNote(remaining.length > 0 ? remaining[0] : null)
    }
  }

  async function handleDownloadPDF() {
    setDownloading(true)
    try {
      const { default: jsPDF } = await import('jspdf')
      const doc = new jsPDF()

      const title = selectedNote.title
      const content = selectedNote.content
      const lines = content.split('\n')

      let y = 20
      const pageHeight = doc.internal.pageSize.height
      const margin = 15
      const maxWidth = 180

      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      doc.text(title, margin, y)
      y += 10

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100)
      doc.text(`Generated by StudyBuddy · ${formatDate(selectedNote.created_at)}`, margin, y)
      y += 10

      doc.setTextColor(0)

      for (const line of lines) {
        if (y > pageHeight - 20) {
          doc.addPage()
          y = 20
        }

        if (line.startsWith('# ')) {
          doc.setFontSize(14)
          doc.setFont('helvetica', 'bold')
          doc.text(line.replace('# ', ''), margin, y)
          y += 8
        } else if (line.startsWith('## ')) {
          doc.setFontSize(12)
          doc.setFont('helvetica', 'bold')
          doc.text(line.replace('## ', ''), margin, y)
          y += 7
        } else if (line.startsWith('### ')) {
          doc.setFontSize(11)
          doc.setFont('helvetica', 'bold')
          doc.text(line.replace('### ', ''), margin, y)
          y += 6
        } else if (line.startsWith('- ') || line.startsWith('• ')) {
          doc.setFontSize(10)
          doc.setFont('helvetica', 'normal')
          const text = '• ' + line.replace(/^[-•]\s*/, '')
          const wrapped = doc.splitTextToSize(text, maxWidth - 5)
          doc.text(wrapped, margin + 3, y)
          y += wrapped.length * 5 + 1
        } else if (line.match(/^\d+\./)) {
          doc.setFontSize(10)
          doc.setFont('helvetica', 'normal')
          const wrapped = doc.splitTextToSize(line, maxWidth - 5)
          doc.text(wrapped, margin + 3, y)
          y += wrapped.length * 5 + 1
        } else if (line.startsWith('|')) {
          doc.setFontSize(9)
          doc.setFont('helvetica', 'normal')
          const cells = line.split('|').filter(c => c.trim() && !c.trim().match(/^[-]+$/))
          if (cells.length > 0) {
            doc.text(cells.join('  |  '), margin, y)
            y += 5
          }
        } else if (line.trim() === '') {
          y += 3
        } else {
          doc.setFontSize(10)
          doc.setFont('helvetica', 'normal')
          const wrapped = doc.splitTextToSize(line, maxWidth)
          doc.text(wrapped, margin, y)
          y += wrapped.length * 5 + 1
        }
      }

      doc.save(`${title.replace(/\s+/g, '_')}_notes.pdf`)
    } catch (e) {
      console.error('PDF generation failed:', e)
    }
    setDownloading(false)
  }

  if (loading) return <LoadingScreen />

  const groups = groupBySubject()

  return (
    <motion.div variants={fadeUp} initial="initial" animate="animate" className="flex flex-col md:flex-row gap-6 h-full">

      {/* Left panel — note list */}
      <div className="w-full md:w-72 flex-shrink-0 flex flex-col gap-4">
        <div>
          <h1 className="text-2xl font-bold app-heading">My Notes</h1>
          <p className="text-sm app-muted mt-1">{notes.length} note{notes.length !== 1 ? 's' : ''} saved</p>
        </div>

        {notes.length === 0 ? (
          <div className="app-card rounded-2xl p-6 text-center" style={{ borderStyle: 'dashed' }}>
            <FileText size={28} className="mx-auto mb-3 app-muted" />
            <div className="text-sm font-semibold app-heading mb-1">No notes yet</div>
            <div className="text-xs app-muted leading-relaxed">Complete a tutor session and generate notes to see them here.</div>
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            {Object.entries(groups).map(([subjectId, subjectNotes]) => (
              <div key={subjectId}>
                <div className="text-xs font-semibold app-muted uppercase tracking-wide mb-2">
                  {getSubjectName(subjectId)}
                </div>
                <div className="flex flex-col gap-2">
                  {subjectNotes.map(note => (
                    <motion.button
                      key={note.id}
                      onClick={() => { setSelectedNote(note); setEditing(false) }}
                      className="text-left px-4 py-3 rounded-xl transition-all"
                      style={{
                        backgroundColor: selectedNote?.id === note.id ? 'var(--primary-soft)' : 'var(--surface)',
                        border: `1px solid ${selectedNote?.id === note.id ? 'var(--primary)' : 'var(--border)'}`,
                      }}
                      whileHover={{ scale: 1.01 }}
                    >
                      <div className="text-sm font-semibold app-heading truncate">{note.title}</div>
                      <div className="text-xs app-muted mt-0.5">{formatDate(note.updated_at)}</div>
                    </motion.button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Right panel — note content */}
      <div className="flex-1 min-w-0">
        {!selectedNote ? (
          <div className="app-card rounded-2xl p-12 text-center h-full flex flex-col items-center justify-center">
            <FileText size={40} className="mb-4 app-muted" />
            <div className="text-sm font-semibold app-heading mb-1">Select a note</div>
            <div className="text-xs app-muted">Choose a note from the left to view it here.</div>
          </div>
        ) : (
          <div className="app-card rounded-2xl p-6 flex flex-col gap-4">

            {/* Header */}
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <h2 className="text-lg font-bold app-heading">{selectedNote.title}</h2>
                <div className="text-xs app-muted mt-1">
                  {getSubjectName(selectedNote.subject_id)} · {formatDate(selectedNote.updated_at)}
                </div>
              </div>
              <div className="flex items-center gap-2 flex-wrap">
                {editing ? (
                  <>
                    <motion.button
                      onClick={handleSave}
                      disabled={saving}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl text-white"
                      style={{ backgroundColor: 'var(--primary)' }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <Check size={14} />
                      {saving ? 'Saving...' : 'Save'}
                    </motion.button>
                    <motion.button
                      onClick={() => { setEditing(false); setEditContent(selectedNote.content) }}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl app-muted"
                      style={{ border: '1px solid var(--border)' }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <X size={14} />
                      Cancel
                    </motion.button>
                  </>
                ) : (
                  <>
                    <motion.button
                      onClick={() => { setEditing(true); setEditContent(selectedNote.content) }}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl app-muted"
                      style={{ border: '1px solid var(--border)' }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <Edit3 size={14} />
                      Edit
                    </motion.button>
                    <motion.button
                      onClick={handleDownloadPDF}
                      disabled={downloading}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl text-white"
                      style={{ backgroundColor: 'var(--primary)' }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <Download size={14} />
                      {downloading ? 'Generating...' : 'Download PDF'}
                    </motion.button>
                    <motion.button
                      onClick={() => handleDelete(selectedNote.id)}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl text-red-400"
                      style={{ border: '1px solid var(--border)' }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <Trash2 size={14} />
                    </motion.button>
                  </>
                )}
              </div>
            </div>

            {/* Content */}
            {editing ? (
              <textarea
                value={editContent}
                onChange={e => setEditContent(e.target.value)}
                className="w-full rounded-xl px-4 py-3 text-sm font-mono transition-all resize-none app-input"
                style={{ minHeight: '500px' }}
              />
            ) : (
              <div className="overflow-y-auto" style={{ maxHeight: 'calc(100vh - 280px)' }}>
                <div className="prose prose-sm max-w-none">
                  {selectedNote.content.split('\n').map((line, i) => {
                    if (line.startsWith('# ')) return <h1 key={i} className="text-xl font-bold app-heading mt-4 mb-2">{line.replace('# ', '')}</h1>
                    if (line.startsWith('## ')) return <h2 key={i} className="text-base font-bold app-heading mt-4 mb-2">{line.replace('## ', '')}</h2>
                    if (line.startsWith('### ')) return <h3 key={i} className="text-sm font-bold app-heading mt-3 mb-1">{line.replace('### ', '')}</h3>
                    if (line.startsWith('- ') || line.startsWith('• ')) return <div key={i} className="flex gap-2 text-sm app-muted my-0.5"><span style={{ color: 'var(--primary)' }}>•</span><span>{line.replace(/^[-•]\s*/, '')}</span></div>
                    if (line.match(/^\d+\./)) return <div key={i} className="text-sm app-muted my-0.5 ml-2">{line}</div>
                    if (line.startsWith('|')) {
                      const cells = line.split('|').filter(c => c.trim())
                      if (cells[0]?.trim().match(/^[-]+$/)) return null
                      return (
                        <div key={i} className="flex gap-4 text-sm py-1 border-b app-muted" style={{ borderColor: 'var(--border)' }}>
                          {cells.map((cell, ci) => <span key={ci} className={ci === 0 ? 'font-semibold app-heading w-32 flex-shrink-0' : 'flex-1'}>{cell.trim()}</span>)}
                        </div>
                      )
                    }
                    if (line.trim() === '') return <div key={i} className="h-2" />
                    return <p key={i} className="text-sm app-muted my-1 leading-relaxed">{line}</p>
                  })}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </motion.div>
  )
}